### PR TITLE
Replace matplotlib APIs removed in 3.11

### LINKED ISSUE #240: Riskfolio-Lib 7.3.0 incompatible with Matplotlib 3.11: Axes.plot_date no longer exists
**Environment:**
- OS: Linux
- Python: 3.12
- riskfolio-lib: 7.3.0
- matplotlib: 3.11.1

**Code:**
```

import riskfolio as rp

rp.jupyter_report(returns, w, rm=rm)
```

**Error:**

```
AttributeError: 'Axes' object has no attribute 'plot_date'

Traceback points to:

riskfolio/src/PlotFunctions.py

line 2584:

i.plot_date(index, data[j], "-", color=color1[j])

Matplotlib 3.11 has removed Axes.plot_date(). Replacing it with

i.plot(index, data[j], "-", color=color1[j])
```

appears to be the appropriate fix since plot() supports datetime axes.

### PR DESCRIPTION
**Pull request by DMZ22**
Closes #240.

`setup.py` allows `matplotlib>=3.9.2`, but **two** APIs the plotting module uses were removed in matplotlib 3.11, so plots raise `AttributeError` on a version the package says it supports.

### 1. `Axes.plot_date` (removed)
Two call sites — `plot_series` (line 209) and `plot_drawdown` (line 2584, the one in the reported traceback). Both pass a `DatetimeIndex` and set an `AutoDateLocator` + `DateFormatter` on the axis immediately afterwards, so `Axes.plot` renders them identically with no other change.

### 2. `matplotlib.cm.get_cmap` (also removed)
Four call sites in `plot_series`, `plot_frontier`, `plot_pie` and `plot_frontier_area`. Switched to `plt.get_cmap`, which is what `AuxFunctions.py` already uses, and dropped the now-unused `cm` import.

### Note on scope
The issue only reports `plot_drawdown`. `plot_series` is broken too — and it actually fails on the colormap lookup *first*, so fixing only `plot_date` still leaves it raising:

```
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```

Both had to go for the module to work on 3.11.

### Verification
On `matplotlib 3.11.1` / `riskfolio-lib 7.3.0`, against the released `PlotFunctions.py` vs this one:

| | before | after |
|---|---|---|
| `plot_drawdown` | `AttributeError: 'Axes' object has no attribute 'plot_date'` | OK |
| `plot_series` | `AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'` | OK |
| `plot_pie`, `plot_bar` | OK | OK (unchanged) |

Both replacements are the migrations matplotlib documents, and neither changes rendering on older supported versions (`plt.get_cmap` and `Axes.plot` have been available throughout the `>=3.9.2` range).

### CODE REVIEW

**Comment by dcajasn** [comment]
I merged a pull request with the same fix.
